
prabha_databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      host: "{{ env_var('DBR_HOST') }}"
      http_path: "{{ env_var('DBR_HTTP_PATH') }}"
      token: "{{ env_var('DBR_TOKEN') }}"
      catalog: "{{ env_var('DBR_CATALOG','hive_metastore') }}"
      schema: "{{ env_var('DBR_SCHEMA','analytics') }}"
      threads: 4
