
version: 2
models:
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
