name: dbt_gold
version: 1.0.0
config-version: 2
profile: dbt_gold
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: target
clean-targets: ["target","dbt_packages"]

models:
  +materialized: view
  marts:
    +schema: marts
